version: "3.9"

services:
  api:
    container_name: api
    build:
      context: ./services/api
      dockerfile: Dockerfile
    ports:
      - "8080:3001"
    networks:
        - app-net

  prometheus:
    container_name: prometheus
    build:
        context: ./services/prometheus
        dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - app-net

  grafana:
    container_name: grafana
    build:
        context: ./services/grafana
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-net

networks:
  app-net: